### ISSUE TITLE
Redesign scripts to build all images from a single branch

### ISSUE THREAD

**Issue by mayeut** [pypa/manylinux#877]
As proposed in https://github.com/pypa/manylinux/issues/542#issue-598574781, this issue is created to propose and track progress of a rewrite of `manylinux` build scripts to build all images from a single branch.

With new `manylinux` policies allowed by PEP600, we'll have more and more images. Creating a branch per policy will cause issues for maintainability and consistency between images (or even README).

`manylinux1` is out-of-scope for the rewrite for now (c.f. https://github.com/pypa/manylinux/issues/542#issuecomment-720674410 for rational)

Here are the steps I propose, feel free to challenge those.
PRs referenced here will build one on top of the other requiring them to be reviewed sequentially.

- [x]  Rework the `manylinux2014` branch to allow for multiple policies
Rational for choosing this as the base branch of the rework: `manylinux2014` branch builds on all platforms which allows to see issues that would otherwise not be seen until a later point.

  - [x] Use graviton2 for arm64 build (#875)
  - [x] Use a single Dockerfile for all images (#876)
  - [x] Rework scripts to be docker cache friendly (mostly for maintainers doing local builds)
    - [x] Round 1 (#879)
    - [x] Round 2 (#965) 
    - [x] Round 3 (#966)
    - [x] Round 4 (#967)
    - [x] Round 5 (#968)
    - [x] Round 6 (#969)
    - [x] Round 7 (#970)
    - [x] Round 8 (#971)
    - [x] Round 9 (#972)
    - [x] Round 10 (#973)
    - [x] Round 11 (#974)
    - [x] Round 12 (#975)
    - [x] Round 13 (#976)
    - [x] Round 14 (#977)
    - [x] Round 15 (#978)
- [x] Merge `manylinux2014` in `master`
At this point, we'll be ready to add new images for newer PEP600 policies
  - [x] Update `glibc` on `manylinux2010` (#874)
  - [x] Publish `quay.io/pypa/manylinux2010_centos-6-no-vsyscall` (#878)
  - [x] Add `manylinux2010` build support in `manylinux2014` branch (#979)
  - [x] Merge in `master` (#993)

- [x] Add `manylinux_2_24` images (#999)
Rational for adding this specific policy: It solves issues for `numpy ppc64le` c.f. https://github.com/pypa/manylinux/issues/542#issue-598574781, `numpy` being the most downloaded `manylinux` package it seems a good starting point as it's also probably used as a dependency in a high number of `manylinux` packages which will thus benefit from this.

@pypa/manylinux, please do provide feedback as your time allows, thanks.

**Comment by manthey** [comment]
With some of these changes, the docker image now has many more layers.  Docker has an upper limit on the total number of layers that an image can have (it is around 128, but I am not certain), and having more layers here mean that downstream docker images that build on it have fewer layers that they can add.  I recognize that having more layers makes these scripts more docker cache friendly for manylinux, but more docker cache hostile for downstream docker images.  Please don't add too many more layers.

**Comment by mayeut** [comment]
@manthey,
I think the total number of layers is 127. This added 31 layers compared to the previous method (now 49 layers, previously 18 layers if I'm not mistaken). If this becomes an issue, I have ideas in order to reduce the number of layers.
We could easily get 5 layers back at no cost. Saving more layers would "cost" storage for cache.
As long as it's not an issue, I'll let things as they are. Thanks for pointing out this potential issue.

**Comment by manthey** [comment]
Thanks, @mayeut.
